[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.normal]
black   = "#1d2021"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[font]
size = 16

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[colors.selection]
background = "#3c3836"
text = "#ebdbb2"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
