[bell]
animation = "EaseOutExpo"
color = "#f38ba8"

duration = 100

[colors.primary]
background = "#282828"  # Gruvbox dark background
foreground = "#ebdbb2"  # Gruvbox light foreground

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 16

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
